name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v1
      with:
        go-version: '1.14.2'
    - name: build
      run: bash mybuild
    - name: download
      uses: actions/upload-artifact@v1
      with:
        name: pcs
        path: BaiduPCS-Go

